apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
      env: production
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
        env: production
        tier: backend
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: prisma
        - name: POSTGRES_USER
          value: prisma
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: postgres
        name: postgres
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 75m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres
